#      ____             ___          __  _ ______      __
#     / __ \_________  /   |  ____  / /_(_)_  __/___ _/ /_
#    / /_/ / ___/ __ \/ /| | / __ \/ __/ / / / / __ `/ __ \
#   / ____/ /  / /_/ / ___ |/ / / / /_/ / / / / /_/ / /_/ /
#  /_/   /_/   \____/_/  |_/_/ /_/\__/_/ /_/  \__,_/_.___/
#  config.yml (Bungeecord version)

# This section doesn't really need to be changed
# but few people seems not to like my design for a custom update-notification message...
# Well... that's basically the whole reason for this one here. xd
updater:
  enabled: true
  period: 18000
  notification:
    - '&8[&4ProAntiTab&8] &cThere is a new version available! (%newest_version%)'
    - '&8[&4ProAntiTab&8] &cYou are still using the %current_version%.'
    - '&8[&4ProAntiTab&8] &cGet the newest version here:'
    - '&8[&4ProAntiTab&8] &ehttps://www.rayzs.de/products/proantitab/page'

# This is a very necessary feature if you have way to many commands to block and instead decides
# to whitelist specific commands.
# Enabling this will disable ALL commands except for those that are in the (group-)list
turn-blacklist-to-whitelist: false

# This feature allows you to customize your server-brand you see when you press F3.
# Normally there stands something like 'Purpur', or 'Spigot'.
# With this feature you are able to change and even animate it! ^^
custom-server-brand:
  # Just replace 'false' with 'true' if you want to enable this feature! ^^
  enabled: false

  # Determines the speed in that the animation goes
  repeat-delay: 150

  # Possible placeholders:
  # %server%        - server-name where the player is
  # %player%        - name of the player
  # %ping%          - ping of player
  brands:
    - '&f&lP&froAntiTab |'
    - '&fP&lr&foAntiTab /'
    - '&fPr&lo&fAntiTab -'
    - '&fPro&lA&fntiTab |'
    - '&fProA&ln&ftiTab \'
    - '&fProAn&lt&fiTab |'
    - '&fProAnt&li&fTab /'
    - '&fProAnti&lT&fab -'
    - '&fProAnti&lT&fab \'
    - '&fProAntiT&la&fb |'
    - '&fProAntiTa&lb&f /'
    - '&fProAntiTab -'
    - '&fProAntiTab \'

# This setting decided if a listed command should be cancelled from execution or not.
# As you can see it's enabled by default, which is also why every command that is listed
# is being blocked entirely.
cancel-blocked-commands:
  enabled: true
  message:
    - '&cThe command "%command%" is blocked!'

# Here you can customize your own fake '/plugins' command ^^
custom-plugins:
  enabled: true
  message:
    - '&fPlugins (0):'

# Now there we come to the good stuff! ^^
# If ProAntiTab is loaded on a Spigot server, you will see this option right here.
# With that you can also customize your own "Unknown Command"-message.
custom-unknown-command:
  enabled: false
  message:
    - '&cThis command does not exist!'

# This one here allows you to see on what servers ProAntiTab has been synced on and when.
# But it's for Bungeecord/Velocity servers only!
stats:
  fail: '&cThis command works on Bungeecord/Velocity servers only!'
  no-server: '&cNone!'
  message:
    splitter: '&7, '
    server: '&f%servername% &8(%updated%)'
    statistic:
      - '&7Last sync sent to &f%server_count% &7servers. &8&o(%last_sync_time% ago)'
      - '&7Sent to servers: &f%servers%'

# ------------------------------------------------------------------------------
#       __  ___
#      /  |/  /__  ______________ _____ ____  _____
#     / /|_/ / _ \/ ___/ ___/ __ `/ __ `/ _ \/ ___/
#    / /  / /  __(__  |__  ) /_/ / /_/ /  __(__  )
#   /_/  /_/\___/____/____/\__,_/\__, /\___/____/
#                               /____/
# Here are all the remaining messages for the InGame commands.
# Have fun editing it to your liking! ^^

no-permissions: '&cYou are not allowed to execute this command! Missing permission: &4proantitab.%permission%'
command-failed: '&cFailed to execute this command! Use "/bpat" to see all available commands.'

notification:
  enabled: '&aEnabled notifications!'
  disabled: '&cDisabled notifications!'
  alert: '&8[&4ALERT&8] &c%player% &8(&7server: &e%server%&8) &ctried to execute the following blocked command: &4%command%'

help:
  - '&7Available commands are: &f/%label%&7...'
  - '&f  reload &7to reload the plugin'
  - '&f  stats &7view when data has been synced'
  - '&f  notify &7to get alerted'
  - '&f  listgroups &7List all groups'
  - '&f  creategroup (group) &7Create a group'
  - '&f  deletegroup (group) &7Delete a group'
  - '&f  list &8(optional: group) &7to see all listed commands'
  - '&f  clear &8(optional: group) &7to clear the list'
  - '&f  add/remove (command) &8(optional: group) &7to manage the list'

reload:
  loading: '&eReloading all configuration files...'
  done: '&aSuccessfully reloaded all configuration files!'

blacklist:
  clear: '&aList has been cleared!'
  clear-confirmation: '&4Warning! &7This command will &cclear the entire list&7! &7Repeat the &esame command &7to confirm this action.'

  list:
    message: '&7Listed commands (&f%size%&7)&8: &f%commands%'
    splitter: '&7, '
    command: '&f'

  add:
    success: '&aSuccessfully added %command% into list!'
    fail: '&c%command% is already in the list!'
    failed: '&c%command% is already in the list!'

  remove:
    success: '&aSuccessfully removed %command% from the list!'
    failed: '&c%command% is not listed!'

group:
  create: '&aGroup %group% has been created!'
  already-exist: '&cGroup %group% already exist!'
  does-not-exist: '&cGroup %group% does not exist!'
  delete: '&cGroup %group% has been deleted!'
  delete-confirmation: '&4Warning! &7This command will &cdelete the group with the whole list&7 of this group! &7Repeat the &esame command &7to confirm this action.'
  clear: '&aList of group %group% has been cleared!'
  clear-confirmation: '&4Warning! &7This command will &cclear the entire list&7 of this group! &7Repeat the &esame command &7to confirm this action.'

  list-groups:
    message: '&7All groups (&f%size%&7)&8: &f%groups%'
    splitter: '&7, '
    group: '&f'

  list:
    message: '&7Listed commands of group %group% (&f%size%&7)&8: &f%commands%'
    splitter: '&7, '
    command: '&f'

  add:
    success: '&aSuccessfully added %command% into the list of group %group%!'
    failed: '&c%command% is already in the list of group %group%!'

  remove:
    success: '&aSuccessfully removed %command% from the list of group %group%!'
    failed: '&c%command% is not listed in the group %group%!'