updater:
  enabled: true
  period: 18000
  notification:
    - '&8[&4ProAntiTab&8] &cYou are using an outdated version of this plugin!'
    - '&8[&4ProAntiTab&8] &cPlease update it on: &ehttps://www.rayzs.de/products/proantitab/page'

turn-blacklist-to-whitelist: false
no-permissions: '&cYou are not allowed to execute this command! Missing permission: &4proantitab.%permission%'
command-failed: '&cFailed to execute this command! Use "/bpat" to see all available commands.'

notification:
  enabled: '&aEnabled notifications!'
  disabled: '&cDisabled notifications!'
  alert: '&8[&4ALERT&8] &c%player% &8(&7server: &e%server%&8) &ctried to execute the following blocked command: &4%command%'

cancel-blocked-commands:
  enabled: true
  message: '&cThe command "%command%" is blocked!'

reload:
  loading: '&eReloading all configuration files...'
  done: '&aSuccessfully reloaded all configuration files!'

blacklist:
  clear: '&aList has been cleared!'
  clear-confirmation: '&4Warning! &7This command will &cclear the entire list&7! &7Repeat the &esame command &7to confirm this action.'

  list:
    message: '&7Listed commands (&f%size%&7)&8: &f%commands%'
    splitter: '&7, '
    command: '&f'
  add:
    success: '&aSuccessfully added %command% into list!'
    failed: '&c%command% is already in the list!'
  remove:
    success: '&aSuccessfully removed %command% from the list!'
    failed: '&c%command% is not listed!'

group:
  create: '&aGroup %group% has been created!'
  already-exist: '&cGroup %group% already exist!'
  does-not-exist: '&cGroup %group% does not exist!'
  delete: '&cGroup %group% has been deleted!'
  delete-confirmation: '&4Warning! &7This command will &cdelete the group with the whole list&7 of this group! &7Repeat the &esame command &7to confirm this action.'
  clear: '&aList of group %group% has been cleared!'
  clear-confirmation: '&4Warning! &7This command will &cclear the entire list&7 of this group! &7Repeat the &esame command &7to confirm this action.'

  list-groups:
    message: '&7All groups (&f%size%&7)&8: &f%groups%'
    splitter: '&7, '
    group: '&f'

  list:
    message: '&7Listed commands of group %group% (&f%size%&7)&8: &f%commands%'
    splitter: '&7, '
    command: '&f'
  add:
    success: '&aSuccessfully added %command% into the list of group %group%!'
    failed: '&c%command% is already in the list of group %group%!'
  remove:
    success: '&aSuccessfully removed %command% from the list of group %group%!'
    fail: '&c%command% is not listed in the group %group%!'
    failed: '&c%command% is not listed in the group %group%!'

help:
  - '&7Available commands are: &f/%label%&7...'
  - '&f  reload &7to reload the plugin'
  - '&f  notify &7to get alerted'
  - '&f  listgroups &7List all groups'
  - '&f  creategroup (group) &7Create a group'
  - '&f  deletegroup (group) &7Delete a group'
  - '&f  list &8(optional: group) &7to see all listed commands'
  - '&f  clear &8(optional: group) &7to clear the list'
  - '&f  add/remove (command) &8(optional: group) &7to manage the list'