# Project properties backend
group = de.rayzs.pat
name = ProAntiTab
main = de.rayzs.pat.plugin.BukkitLoader
version = 2.5.1
description = Hides more than just your plugins.
website = https://www.rayzs.de/products/proantitab/page
author = Rayzs_YT
apiVersion = 1.13
foliaSupported = true

# Project properties proxy
bungeeMain = de.rayzs.pat.plugin.BungeeLoader

# Gradle properties
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx3G -XX:+UseG1GC -Dfile.encoding=UTF-8
