name: ${name}
description: ${description}
website: ${website}

author: ${author}
version: "${version}"
api-version: "${apiVersion}"
folia-supported: ${foliaSupported}
main: ${main}

softdepend:
  [
    PlaceholderAPI,
    LuckPerms,
    GroupManager,
    Skript,
    ViaVersion,
    ViaBackwards,
    ViaRewind,
  ]

commands:
  proantitab:
    description: Main command for the plugin
    aliases: pat
    permission: proantitab.use
