name: ProAntiTab
description: A simple structured AntiTab plugin to prevent specific commands from being executed and auto-tab-completed.

author: Rayzs_YT
version: 1.6.1
api-version: 1.13
main: de.rayzs.pat.plugin.BukkitLoader

softdepend:
  - PlaceholderAPI
  - LuckPerms

commands:
  proantitab:
    aliases: [pat]