name: ProAntiTab
description: Hide more then just plugins. Hide almost everything!

author: Rayzs_YT
version: 1.7.5
api-version: 1.13
main: de.rayzs.pat.plugin.BukkitLoader

softdepend:
  - PlaceholderAPI
  - LuckPerms
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Skript

commands:
  proantitab:
    aliases: [pat]