name: ProAntiTab
description: A simple strucutured AntiTab plugin to prevent specific commands from being executed and auto-tab-completed.

author: Rayzs_YT
version: 1.3.0
api-version: 1.13
main: de.rayzs.pat.plugin.BukkitLoader

commands:
  proantitab:
    aliases: [pat]