name: ProAntiTab
description: Hides more than just your plugins.
website: https://www.rayzs.de/products/proantitab/page

author: Rayzs_YT
version: 2.3.1
api-version: 1.13
folia-supported: true
main: de.rayzs.pat.plugin.BukkitLoader

softdepend: [PlaceholderAPI, LuckPerms, GroupManager, Skript, ViaVersion, ViaBackwards, ViaRewind]

commands:
  proantitab:
    aliases: [pat]